title: Wan  Huihui's Homepage
page-top-title: Wan Huihui
top-section-bg-text: Journalism and Communication-Journalism
home-subtitle: Wan Huihui|万辉辉
copyright-text: '&copy;  Wan Huihui2024-2025. All Rights Reserved.'
